pool:
  name: Azure Pipelines
steps:
- task: NodeTool@0
  displayName: Node
  inputs:
    versionSpec: 10.x

- task: Npm@1
  displayName: 'angular cli'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install @angular/cli -g'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'production build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: Spotly'
  inputs:
    azureSubscription: 'Azure subscription 1 (4f7fbd4e-fdd8-4127-9480-e01b344eb872)'
    WebAppName: Spotly
    packageForLinux: '''$(System.ArtifactsDirectory)'''

- task: PublishBuildArtifacts@1